<?php

namespace AppBundle\Repository;

/**
 * ImovelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImovelRepository extends \Doctrine\ORM\EntityRepository
{
}
